import{a as f,S as y,i as a}from"./assets/vendor-BnUHvSuA.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const c of e.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function r(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function n(t){if(t.ep)return;t.ep=!0;const e=r(t);fetch(t.href,e)}})();const g="48918931-19353ebecebc74a7aac5f0327",L="https://pixabay.com/api/",p=async(s,o=1)=>{try{return(await f.get(L,{params:{key:g,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:40}})).data}catch(r){return console.error("Error fetching images: ",r),{hits:[],totalHits:0}}};let v=new y(".gallery a"),u=0;const l=document.querySelector(".gallery"),d=document.querySelector(".load-more");document.querySelector(".loader");const h=async(s,o,r=!1)=>{if(r&&(l.innerHTML="",u=o),s.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),d.classList.add("hidden");return}const n=s.map(e=>`
    <div class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" />
      </a>
      <div class="info">
        <p>Likes<span>${e.likes}</span></p>
        <p>Views <span>${e.views}</span></p>
        <p>Comments<span>${e.comments}</span></p>
        <p>Downloads<span>${e.downloads}</span></p>
      </div>
    </div>
  `).join("");l.insertAdjacentHTML("beforeend",n),await v.refresh(),l.children.length>=u?(d.classList.add("hidden"),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):d.classList.remove("hidden");const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})},q=()=>{},w=document.querySelector("#search-form"),m=document.querySelector("#search-input"),b=document.querySelector(".load-more"),i=document.querySelector(".loader");w.addEventListener("submit",async s=>{s.preventDefault();const o=m.value.trim();if(!o){a.warning({title:"Warning",message:"Please enter a search query."});return}i.classList.remove("hidden");try{const r=await p(o,1);h(r.hits,r.totalHits,!0)}catch{a.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}finally{i.classList.add("hidden")}});b.addEventListener("click",async()=>{const s=q(),o=m.value.trim();i.classList.remove("hidden");try{const r=await p(o,s);h(r.hits,r.totalHits)}catch{a.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}finally{i.classList.add("hidden")}});
//# sourceMappingURL=index.js.map
