import{a as y,S as f,i as n}from"./assets/vendor-BnUHvSuA.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const c of e.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function a(t){if(t.ep)return;t.ep=!0;const e=o(t);fetch(t.href,e)}})();const g="48918931-19353ebecebc74a7aac5f0327",L="https://pixabay.com/api/",p=async(s,r=1)=>{try{return(await y.get(L,{params:{key:g,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:40}})).data}catch(o){return console.error("Error fetching images: ",o),{hits:[],totalHits:0}}};let v=new f(".gallery a"),u=0;const l=document.querySelector(".gallery"),d=document.querySelector(".load-more");document.querySelector(".loader");const h=async(s,r,o=!1)=>{if(o&&(l.innerHTML="",u=r),s.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),d.classList.add("hidden");return}const a=s.map(e=>`
    <div class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" />
      </a>
      <div class="info">
        <p>Likes<span>${e.likes}</span></p>
        <p>Views <span>${e.views}</span></p>
        <p>Comments<span>${e.comments}</span></p>
        <p>Downloads<span>${e.downloads}</span></p>
      </div>
    </div>
  `).join("");l.insertAdjacentHTML("beforeend",a),await v.refresh(),l.children.length>=u?(d.classList.add("hidden"),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):d.classList.remove("hidden");const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})},q=()=>{},w=document.querySelector("#search-form"),m=document.querySelector("#search-input"),S=document.querySelector(".load-more"),i=document.querySelector(".loader");w.addEventListener("submit",async s=>{s.preventDefault();const r=m.value.trim(),o=document.querySelector(".gallery");if(o.innerHTML="",!r){n.warning({title:"Warning",message:"Please enter a search query."});return}i.classList.remove("hidden");try{const a=await p(r,1);h(a.hits,a.totalHits,!0)}catch{n.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}finally{i.classList.add("hidden")}});S.addEventListener("click",async()=>{const s=q(),r=m.value.trim();i.classList.remove("hidden");try{const o=await p(r,s);h(o.hits,o.totalHits)}catch{n.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}finally{i.classList.add("hidden")}});
//# sourceMappingURL=index.js.map
